CREATE TABLE public.post (
	id int NOT NULL GENERATED ALWAYS AS IDENTITY,
	title text NOT NULL,
	"user" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" text NOT NULL,
	category int NOT NULL,
	updated time NOT NULL,
	created time NOT NULL,
	CONSTRAINT post_pk PRIMARY KEY (id),
	CONSTRAINT post_fk_1 FOREIGN KEY (category) REFERENCES public.category(id),
	CONSTRAINT post_fk FOREIGN KEY ("user") REFERENCES public."user"(id)
);

CREATE TABLE public.category (
	id int NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (id),
	CONSTRAINT category_un UNIQUE (id),
	CONSTRAINT category_un UNIQUE ("name")
);

CREATE TABLE public."comment" (
	id int NOT NULL,
	"content" text NOT NULL,
	post int NOT NULL,
	"user" int NOT NULL,
	created time NOT NULL,
	updated time NOT NULL,
	CONSTRAINT comment_pk PRIMARY KEY (id),
	CONSTRAINT comment_un UNIQUE (id),
	CONSTRAINT comment_fk FOREIGN KEY (post) REFERENCES public.post(id),
	CONSTRAINT comment_fk_1 FOREIGN KEY ("user") REFERENCES public."user"(id)
);

CREATE TABLE public."user" (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"password" text NOT NULL,
	email text NOT NULL,
	created time NOT NULL,
	updated time NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_un UNIQUE (id,"password",email)
);
